name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: install rustfmt
        run: rustup component add rustfmt

      - name: rustfmt check
        run: cargo fmt --all -- --check

  macos-latest-stable:
    needs: [format]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  macos-latest-nightly:
    needs: [format]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  windows-latest-stable:
    needs: [format]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  windows-latest-nightly:
    needs: [format]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  coveralls-coverage-report:
    needs: [format]
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets

  ubuntu-latest-nightly:
    needs: [format]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test