name: publish

env:
  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

on:
  workflow_dispatch:
    inputs:
      tag-increment:
        description: increment version tag
        default: patch
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      # repo write permission for pushing tags
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt,clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -W clippy::pedantic
      - run: cargo test
      - run: cargo install cargo-bump
      - run: cargo bump -g ${{ inputs.tag-increment }}
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'Cargo.lock'
          push: true
      - run: git diff
      - run: cargo publish --token ${{ secrets.CARGO_TOKEN }}