name: publish

env:
  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

on:
  workflow_dispatch:
    workflows: [ci]
    branches: [main]
    types:
      - completed
    inputs:
      tag-increment:
        description: increment version tag
        default: patch
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      # repo write permission for pushing tags
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-bump
      - run: cargo bump -g ${{ inputs.tag-increment }}
      - run: git push && git push --tags
      - run: cargo publish --token ${{ secrets.CARGO_TOKEN }}