name: publish

env:
  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

on:
  workflow_dispatch:
    inputs:
      tag-increment:
        description: increment version tag
        default: patch
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: macos-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features --all-targets
      - run: cargo test
      - run: cargo install cargo-bump
      - run: cargo bump -g ${{ inputs.tag-increment }}
      - run: git push && git push --tags
      - run: cargo publish --token ${{ secrets.CARGO_TOKEN }}